# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

appearance:
  mode: system
  color: blue

extensions:
  academicons:
    enable: true

assets:
  custom_css_files:
    - css/hero-stroke.css      # <- will load assets/css/hero-stroke.css
    - css/custom.css           # <- will load assets/css/custom.css

icon:
  packs:
    - fas   # Font Awesome 5/6 SOLID (required for "envelope", etc.)
    - fab   # Font Awesome BRANDS (LinkedIn, GitHub, etc.)
    - ai    # Academic Icons (Google-Scholar, CV)
    - custom # Custom icons stored in assets/media/icons

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Georgia State University'
    description: 'Dr. Benjamin M. Ampel - Assistant Professor of Computer Information Systems at Georgia State University. Leading researcher in AI-powered cybersecurity, specializing in large-scale text analytics for cyber threat intelligence. 400+ citations, Best Paper Awards, and publications in top-tier journals including MIS Quarterly and JMIS.'
    keywords: "cybersecurity, AI, machine learning, threat intelligence, Georgia State University, Benjamin Ampel, computer information systems, research, academic"
    author: "Dr. Benjamin M. Ampel"
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: true
    logo:
      text: "Dr. Benjamin M. Ampel"

# Site footer
footer:
  copyright:
    notice: '© {year} Dr. Benjamin M. Ampel. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
